version: '3'

services :
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/usr/src/app/_static
            - media_volume:/usr/src/app_/media
        ports:
            - 80:80
        depends_on:
            - web
    
    web :
        build: .
        command: gunicorn do_it_django_prj.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/usr/src/app/_static
            - media_volume:/usr/src/app_/media
            - ./:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.prod
        depends_on:
            - db

    db :
        image: postgres:15.6-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db

volumes :
    postgres_data:
    static_volume:
    media_volume: